/* Generated by tools/tarot_assets/generate.py. Public tarot asset API. */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define TAROT_CARD_COUNT 78u
#define TAROT_CARD_WIDTH 272u
#define TAROT_CARD_HEIGHT 464u
#define TAROT_CARD_STRIDE 34u
#define TAROT_CARD_DATA_SIZE 15784u

typedef struct {
    const char *id;
    const char *name_ko;
    const char *name_en;
    const char *arcana;
    const char *suit;
    const char *rank;
} tarot_card_metadata_t;

/* Returned descriptors are exact-size I1 assets and must not be scaled. */
const lv_image_dsc_t *tarot_card_image(const char *id);
const tarot_card_metadata_t *tarot_card_metadata(const char *id);

#ifdef __cplusplus
}
#endif
