/* Generated by tools/tarot_assets/generate.py. Do not edit. */
#include "tarot_cards.h"

#include <stddef.h>
#include <string.h>

extern const lv_image_dsc_t tarot_major_00;
extern const lv_image_dsc_t tarot_major_01;
extern const lv_image_dsc_t tarot_major_02;
extern const lv_image_dsc_t tarot_major_03;
extern const lv_image_dsc_t tarot_major_04;
extern const lv_image_dsc_t tarot_major_05;
extern const lv_image_dsc_t tarot_major_06;
extern const lv_image_dsc_t tarot_major_07;
extern const lv_image_dsc_t tarot_major_08;
extern const lv_image_dsc_t tarot_major_09;
extern const lv_image_dsc_t tarot_major_10;
extern const lv_image_dsc_t tarot_major_11;
extern const lv_image_dsc_t tarot_major_12;
extern const lv_image_dsc_t tarot_major_13;
extern const lv_image_dsc_t tarot_major_14;
extern const lv_image_dsc_t tarot_major_15;
extern const lv_image_dsc_t tarot_major_16;
extern const lv_image_dsc_t tarot_major_17;
extern const lv_image_dsc_t tarot_major_18;
extern const lv_image_dsc_t tarot_major_19;
extern const lv_image_dsc_t tarot_major_20;
extern const lv_image_dsc_t tarot_major_21;
extern const lv_image_dsc_t tarot_cups_01;
extern const lv_image_dsc_t tarot_cups_02;
extern const lv_image_dsc_t tarot_cups_03;
extern const lv_image_dsc_t tarot_cups_04;
extern const lv_image_dsc_t tarot_cups_05;
extern const lv_image_dsc_t tarot_cups_06;
extern const lv_image_dsc_t tarot_cups_07;
extern const lv_image_dsc_t tarot_cups_08;
extern const lv_image_dsc_t tarot_cups_09;
extern const lv_image_dsc_t tarot_cups_10;
extern const lv_image_dsc_t tarot_cups_11;
extern const lv_image_dsc_t tarot_cups_12;
extern const lv_image_dsc_t tarot_cups_13;
extern const lv_image_dsc_t tarot_cups_14;
extern const lv_image_dsc_t tarot_pentacles_01;
extern const lv_image_dsc_t tarot_pentacles_02;
extern const lv_image_dsc_t tarot_pentacles_03;
extern const lv_image_dsc_t tarot_pentacles_04;
extern const lv_image_dsc_t tarot_pentacles_05;
extern const lv_image_dsc_t tarot_pentacles_06;
extern const lv_image_dsc_t tarot_pentacles_07;
extern const lv_image_dsc_t tarot_pentacles_08;
extern const lv_image_dsc_t tarot_pentacles_09;
extern const lv_image_dsc_t tarot_pentacles_10;
extern const lv_image_dsc_t tarot_pentacles_11;
extern const lv_image_dsc_t tarot_pentacles_12;
extern const lv_image_dsc_t tarot_pentacles_13;
extern const lv_image_dsc_t tarot_pentacles_14;
extern const lv_image_dsc_t tarot_swords_01;
extern const lv_image_dsc_t tarot_swords_02;
extern const lv_image_dsc_t tarot_swords_03;
extern const lv_image_dsc_t tarot_swords_04;
extern const lv_image_dsc_t tarot_swords_05;
extern const lv_image_dsc_t tarot_swords_06;
extern const lv_image_dsc_t tarot_swords_07;
extern const lv_image_dsc_t tarot_swords_08;
extern const lv_image_dsc_t tarot_swords_09;
extern const lv_image_dsc_t tarot_swords_10;
extern const lv_image_dsc_t tarot_swords_11;
extern const lv_image_dsc_t tarot_swords_12;
extern const lv_image_dsc_t tarot_swords_13;
extern const lv_image_dsc_t tarot_swords_14;
extern const lv_image_dsc_t tarot_wands_01;
extern const lv_image_dsc_t tarot_wands_02;
extern const lv_image_dsc_t tarot_wands_03;
extern const lv_image_dsc_t tarot_wands_04;
extern const lv_image_dsc_t tarot_wands_05;
extern const lv_image_dsc_t tarot_wands_06;
extern const lv_image_dsc_t tarot_wands_07;
extern const lv_image_dsc_t tarot_wands_08;
extern const lv_image_dsc_t tarot_wands_09;
extern const lv_image_dsc_t tarot_wands_10;
extern const lv_image_dsc_t tarot_wands_11;
extern const lv_image_dsc_t tarot_wands_12;
extern const lv_image_dsc_t tarot_wands_13;
extern const lv_image_dsc_t tarot_wands_14;

typedef struct {
    tarot_card_metadata_t metadata;
    const lv_image_dsc_t *image;
} tarot_card_entry_t;

static const tarot_card_entry_t catalog[TAROT_CARD_COUNT] = {
    { { "major-00", "바보", "The Fool", "major", NULL, NULL }, &tarot_major_00 },
    { { "major-01", "마법사", "The Magician", "major", NULL, NULL }, &tarot_major_01 },
    { { "major-02", "여사제", "The High Priestess", "major", NULL, NULL }, &tarot_major_02 },
    { { "major-03", "여제", "The Empress", "major", NULL, NULL }, &tarot_major_03 },
    { { "major-04", "황제", "The Emperor", "major", NULL, NULL }, &tarot_major_04 },
    { { "major-05", "교황", "The Hierophant", "major", NULL, NULL }, &tarot_major_05 },
    { { "major-06", "연인", "The Lovers", "major", NULL, NULL }, &tarot_major_06 },
    { { "major-07", "전차", "The Chariot", "major", NULL, NULL }, &tarot_major_07 },
    { { "major-08", "힘", "Strength", "major", NULL, NULL }, &tarot_major_08 },
    { { "major-09", "은둔자", "The Hermit", "major", NULL, NULL }, &tarot_major_09 },
    { { "major-10", "운명의 수레바퀴", "Wheel of Fortune", "major", NULL, NULL }, &tarot_major_10 },
    { { "major-11", "정의", "Justice", "major", NULL, NULL }, &tarot_major_11 },
    { { "major-12", "매달린 사람", "The Hanged Man", "major", NULL, NULL }, &tarot_major_12 },
    { { "major-13", "죽음", "Death", "major", NULL, NULL }, &tarot_major_13 },
    { { "major-14", "절제", "Temperance", "major", NULL, NULL }, &tarot_major_14 },
    { { "major-15", "악마", "The Devil", "major", NULL, NULL }, &tarot_major_15 },
    { { "major-16", "탑", "The Tower", "major", NULL, NULL }, &tarot_major_16 },
    { { "major-17", "별", "The Star", "major", NULL, NULL }, &tarot_major_17 },
    { { "major-18", "달", "The Moon", "major", NULL, NULL }, &tarot_major_18 },
    { { "major-19", "태양", "The Sun", "major", NULL, NULL }, &tarot_major_19 },
    { { "major-20", "심판", "Judgement", "major", NULL, NULL }, &tarot_major_20 },
    { { "major-21", "세계", "The World", "major", NULL, NULL }, &tarot_major_21 },
    { { "cups-01", "컵 에이스", "Ace of Cups", "minor", "cups", "ace" }, &tarot_cups_01 },
    { { "cups-02", "컵 2", "Two of Cups", "minor", "cups", "two" }, &tarot_cups_02 },
    { { "cups-03", "컵 3", "Three of Cups", "minor", "cups", "three" }, &tarot_cups_03 },
    { { "cups-04", "컵 4", "Four of Cups", "minor", "cups", "four" }, &tarot_cups_04 },
    { { "cups-05", "컵 5", "Five of Cups", "minor", "cups", "five" }, &tarot_cups_05 },
    { { "cups-06", "컵 6", "Six of Cups", "minor", "cups", "six" }, &tarot_cups_06 },
    { { "cups-07", "컵 7", "Seven of Cups", "minor", "cups", "seven" }, &tarot_cups_07 },
    { { "cups-08", "컵 8", "Eight of Cups", "minor", "cups", "eight" }, &tarot_cups_08 },
    { { "cups-09", "컵 9", "Nine of Cups", "minor", "cups", "nine" }, &tarot_cups_09 },
    { { "cups-10", "컵 10", "Ten of Cups", "minor", "cups", "ten" }, &tarot_cups_10 },
    { { "cups-11", "컵 시종", "Page of Cups", "minor", "cups", "page" }, &tarot_cups_11 },
    { { "cups-12", "컵 기사", "Knight of Cups", "minor", "cups", "knight" }, &tarot_cups_12 },
    { { "cups-13", "컵 여왕", "Queen of Cups", "minor", "cups", "queen" }, &tarot_cups_13 },
    { { "cups-14", "컵 왕", "King of Cups", "minor", "cups", "king" }, &tarot_cups_14 },
    { { "pentacles-01", "펜타클 에이스", "Ace of Pentacles", "minor", "pentacles", "ace" }, &tarot_pentacles_01 },
    { { "pentacles-02", "펜타클 2", "Two of Pentacles", "minor", "pentacles", "two" }, &tarot_pentacles_02 },
    { { "pentacles-03", "펜타클 3", "Three of Pentacles", "minor", "pentacles", "three" }, &tarot_pentacles_03 },
    { { "pentacles-04", "펜타클 4", "Four of Pentacles", "minor", "pentacles", "four" }, &tarot_pentacles_04 },
    { { "pentacles-05", "펜타클 5", "Five of Pentacles", "minor", "pentacles", "five" }, &tarot_pentacles_05 },
    { { "pentacles-06", "펜타클 6", "Six of Pentacles", "minor", "pentacles", "six" }, &tarot_pentacles_06 },
    { { "pentacles-07", "펜타클 7", "Seven of Pentacles", "minor", "pentacles", "seven" }, &tarot_pentacles_07 },
    { { "pentacles-08", "펜타클 8", "Eight of Pentacles", "minor", "pentacles", "eight" }, &tarot_pentacles_08 },
    { { "pentacles-09", "펜타클 9", "Nine of Pentacles", "minor", "pentacles", "nine" }, &tarot_pentacles_09 },
    { { "pentacles-10", "펜타클 10", "Ten of Pentacles", "minor", "pentacles", "ten" }, &tarot_pentacles_10 },
    { { "pentacles-11", "펜타클 시종", "Page of Pentacles", "minor", "pentacles", "page" }, &tarot_pentacles_11 },
    { { "pentacles-12", "펜타클 기사", "Knight of Pentacles", "minor", "pentacles", "knight" }, &tarot_pentacles_12 },
    { { "pentacles-13", "펜타클 여왕", "Queen of Pentacles", "minor", "pentacles", "queen" }, &tarot_pentacles_13 },
    { { "pentacles-14", "펜타클 왕", "King of Pentacles", "minor", "pentacles", "king" }, &tarot_pentacles_14 },
    { { "swords-01", "소드 에이스", "Ace of Swords", "minor", "swords", "ace" }, &tarot_swords_01 },
    { { "swords-02", "소드 2", "Two of Swords", "minor", "swords", "two" }, &tarot_swords_02 },
    { { "swords-03", "소드 3", "Three of Swords", "minor", "swords", "three" }, &tarot_swords_03 },
    { { "swords-04", "소드 4", "Four of Swords", "minor", "swords", "four" }, &tarot_swords_04 },
    { { "swords-05", "소드 5", "Five of Swords", "minor", "swords", "five" }, &tarot_swords_05 },
    { { "swords-06", "소드 6", "Six of Swords", "minor", "swords", "six" }, &tarot_swords_06 },
    { { "swords-07", "소드 7", "Seven of Swords", "minor", "swords", "seven" }, &tarot_swords_07 },
    { { "swords-08", "소드 8", "Eight of Swords", "minor", "swords", "eight" }, &tarot_swords_08 },
    { { "swords-09", "소드 9", "Nine of Swords", "minor", "swords", "nine" }, &tarot_swords_09 },
    { { "swords-10", "소드 10", "Ten of Swords", "minor", "swords", "ten" }, &tarot_swords_10 },
    { { "swords-11", "소드 시종", "Page of Swords", "minor", "swords", "page" }, &tarot_swords_11 },
    { { "swords-12", "소드 기사", "Knight of Swords", "minor", "swords", "knight" }, &tarot_swords_12 },
    { { "swords-13", "소드 여왕", "Queen of Swords", "minor", "swords", "queen" }, &tarot_swords_13 },
    { { "swords-14", "소드 왕", "King of Swords", "minor", "swords", "king" }, &tarot_swords_14 },
    { { "wands-01", "완드 에이스", "Ace of Wands", "minor", "wands", "ace" }, &tarot_wands_01 },
    { { "wands-02", "완드 2", "Two of Wands", "minor", "wands", "two" }, &tarot_wands_02 },
    { { "wands-03", "완드 3", "Three of Wands", "minor", "wands", "three" }, &tarot_wands_03 },
    { { "wands-04", "완드 4", "Four of Wands", "minor", "wands", "four" }, &tarot_wands_04 },
    { { "wands-05", "완드 5", "Five of Wands", "minor", "wands", "five" }, &tarot_wands_05 },
    { { "wands-06", "완드 6", "Six of Wands", "minor", "wands", "six" }, &tarot_wands_06 },
    { { "wands-07", "완드 7", "Seven of Wands", "minor", "wands", "seven" }, &tarot_wands_07 },
    { { "wands-08", "완드 8", "Eight of Wands", "minor", "wands", "eight" }, &tarot_wands_08 },
    { { "wands-09", "완드 9", "Nine of Wands", "minor", "wands", "nine" }, &tarot_wands_09 },
    { { "wands-10", "완드 10", "Ten of Wands", "minor", "wands", "ten" }, &tarot_wands_10 },
    { { "wands-11", "완드 시종", "Page of Wands", "minor", "wands", "page" }, &tarot_wands_11 },
    { { "wands-12", "완드 기사", "Knight of Wands", "minor", "wands", "knight" }, &tarot_wands_12 },
    { { "wands-13", "완드 여왕", "Queen of Wands", "minor", "wands", "queen" }, &tarot_wands_13 },
    { { "wands-14", "완드 왕", "King of Wands", "minor", "wands", "king" }, &tarot_wands_14 },
};

static const tarot_card_entry_t *find_card(const char *id)
{
    if(id == NULL) return NULL;
    for(size_t i = 0; i < TAROT_CARD_COUNT; ++i) {
        if(strcmp(catalog[i].metadata.id, id) == 0) return &catalog[i];
    }
    return NULL;
}

const lv_image_dsc_t *tarot_card_image(const char *id)
{
    const tarot_card_entry_t *entry = find_card(id);
    return entry ? entry->image : NULL;
}

const tarot_card_metadata_t *tarot_card_metadata(const char *id)
{
    const tarot_card_entry_t *entry = find_card(id);
    return entry ? &entry->metadata : NULL;
}
