#!/usr/bin/env python3
"""Contract tests for generated 1-bit tarot assets.

The source JPEGs intentionally do not live in this repository.  These tests
exercise the checked-in manifest, generated byte arrays, and public C API so a
normal build never needs the network, Pillow, or ImageMagick.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import tempfile
import textwrap
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "components" / "vault_core" / "assets" / "tarot"
INCLUDE_DIR = ROOT / "components" / "vault_core" / "include"
MANIFEST_PATH = ROOT / "tools" / "tarot_assets" / "manifest.json"

WIDTH = 272
HEIGHT = 464
STRIDE = 34
PALETTE = bytes((0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0xFF))
DATA_SIZE = 8 + STRIDE * HEIGHT


def expected_ids() -> list[str]:
    ids = [f"major-{number:02d}" for number in range(22)]
    for suit in ("cups", "pentacles", "swords", "wands"):
        ids.extend(f"{suit}-{number:02d}" for number in range(1, 15))
    return ids


def load_manifest() -> dict:
    if not MANIFEST_PATH.is_file():
        raise AssertionError(f"generated tarot manifest is missing: {MANIFEST_PATH}")
    with MANIFEST_PATH.open(encoding="utf-8") as stream:
        return json.load(stream)


def parse_generated_arrays() -> dict[str, bytes]:
    arrays: dict[str, bytes] = {}
    array_pattern = re.compile(
        r"(?:static\s+)?const\s+uint8_t\s+(tarot_[a-z0-9_]+_map)\[\]\s*=\s*\{(.*?)\};",
        re.DOTALL,
    )
    for source_path in sorted(ASSET_DIR.glob("*.c")):
        source = source_path.read_text(encoding="utf-8")
        for symbol, body in array_pattern.findall(source):
            values = bytes(int(value, 16) for value in re.findall(r"0x([0-9a-fA-F]{2})", body))
            if symbol in arrays:
                raise AssertionError(f"duplicate generated array: {symbol}")
            arrays[symbol] = values
    return arrays


class TarotAssetTests(unittest.TestCase):
    def test_manifest_has_all_unique_card_ids_and_pinned_provenance(self) -> None:
        manifest = load_manifest()
        cards = manifest["cards"]
        ids = [card["id"] for card in cards]

        self.assertEqual(78, len(cards))
        self.assertEqual(78, len(set(ids)))
        self.assertEqual(set(expected_ids()), set(ids))

        source = manifest["source"]
        self.assertEqual("https://github.com/yunruse/tarot", source["repository"])
        self.assertEqual("develop", source["branch"])
        self.assertRegex(source["commit"], r"^[0-9a-f]{40}$")
        self.assertEqual("CC0-1.0", source["license"])
        self.assertEqual("cards/bw", source["path"])

        transform = manifest["transform"]
        self.assertEqual(WIDTH, transform["width"])
        self.assertEqual(HEIGHT, transform["height"])
        self.assertEqual(STRIDE, transform["stride"])
        self.assertEqual("ordered", transform["dither"])
        self.assertEqual("msb-first", transform["bit_order"])
        self.assertEqual("white", transform["palette_index_0"])
        self.assertEqual("black", transform["palette_index_1"])
        self.assertRegex(transform["imagemagick_version"], r"^ImageMagick 7\.")
        self.assertIn("-ordered-dither", transform["command"])

        commit = source["commit"]
        for card in cards:
            with self.subTest(card=card["id"]):
                self.assertRegex(card["source_sha256"], r"^[0-9a-f]{64}$")
                self.assertRegex(card["payload_sha256"], r"^[0-9a-f]{64}$")
                self.assertTrue(card["source_file"].endswith(".jpg"))
                self.assertEqual(
                    f"https://media.githubusercontent.com/media/yunruse/tarot/{commit}/cards/bw/{card['source_file']}",
                    card["source_url"],
                )
                self.assertTrue(card["name_en"])
                self.assertTrue(card["name_ko"])
                self.assertIn(card["arcana"], ("major", "minor"))
                self.assertIn(card["generated_file"], {
                    "major.c", "cups.c", "pentacles.c", "swords.c", "wands.c"
                })
                self.assertRegex(card["symbol"], r"^tarot_[a-z0-9_]+$")

    def test_generated_arrays_have_exact_i1_payload_and_polarity(self) -> None:
        manifest = load_manifest()
        arrays = parse_generated_arrays()

        self.assertEqual(78, len(arrays))
        for card in manifest["cards"]:
            map_symbol = card["symbol"] + "_map"
            with self.subTest(card=card["id"]):
                payload = arrays[map_symbol]
                self.assertEqual(DATA_SIZE, len(payload))
                self.assertEqual(PALETTE, payload[:8])
                self.assertEqual(card["payload_sha256"], hashlib.sha256(payload).hexdigest())
                pixels = payload[8:]
                self.assertNotEqual(bytes(len(pixels)), pixels, "card cannot be all white")
                self.assertNotEqual(bytes((0xFF,)) * len(pixels), pixels, "card cannot be all black")

    def test_public_catalog_and_descriptors_compile_and_execute(self) -> None:
        manifest = load_manifest()
        asset_sources = [
            ASSET_DIR / name
            for name in ("major.c", "cups.c", "pentacles.c", "swords.c", "wands.c", "catalog.c")
        ]
        for path in asset_sources:
            self.assertTrue(path.is_file(), path)

        ids_literal = ",\n".join(f'    "{card_id}"' for card_id in expected_ids())
        stub_lvgl = textwrap.dedent(
            """
            #pragma once
            #include <stdint.h>
            #include <stddef.h>
            #define LV_IMAGE_HEADER_MAGIC 0x19u
            #define LV_COLOR_FORMAT_I1 0x07u
            #define LV_ATTRIBUTE_MEM_ALIGN
            #define LV_ATTRIBUTE_LARGE_CONST
            typedef struct {
                uint32_t magic;
                uint32_t cf;
                uint32_t flags;
                uint32_t w;
                uint32_t h;
                uint32_t stride;
                uint32_t reserved_2;
            } lv_image_header_t;
            typedef struct {
                lv_image_header_t header;
                uint32_t data_size;
                const uint8_t *data;
                const void *reserved;
                const void *reserved_2;
            } lv_image_dsc_t;
            """
        )
        harness = textwrap.dedent(
            f"""
            #include <stddef.h>
            #include <stdint.h>
            #include <string.h>
            #include "tarot_cards.h"

            static const char * const ids[] = {{
            {ids_literal}
            }};

            int main(void) {{
                if(TAROT_CARD_COUNT != 78u || TAROT_CARD_WIDTH != 272u ||
                   TAROT_CARD_HEIGHT != 464u || TAROT_CARD_STRIDE != 34u ||
                   TAROT_CARD_DATA_SIZE != 15784u) return 1;
                for(size_t i = 0; i < TAROT_CARD_COUNT; ++i) {{
                    const lv_image_dsc_t *image = tarot_card_image(ids[i]);
                    const tarot_card_metadata_t *metadata = tarot_card_metadata(ids[i]);
                    if(!image || !metadata) return 2;
                    if(strcmp(metadata->id, ids[i]) != 0 || !metadata->name_en[0] || !metadata->name_ko[0]) return 3;
                    if(image->header.magic != LV_IMAGE_HEADER_MAGIC ||
                       image->header.cf != LV_COLOR_FORMAT_I1 || image->header.flags != 0u ||
                       image->header.w != 272u || image->header.h != 464u || image->header.stride != 34u ||
                       image->data_size != 15784u || !image->data) return 4;
                    if(memcmp(image->data, "\\xff\\xff\\xff\\xff\\x00\\x00\\x00\\xff", 8) != 0) return 5;
                }}
                if(tarot_card_image("missing-99") != NULL || tarot_card_metadata("missing-99") != NULL) return 6;
                if(tarot_card_image(NULL) != NULL || tarot_card_metadata(NULL) != NULL) return 7;
                return 0;
            }}
            """
        )

        with tempfile.TemporaryDirectory() as temp_dir_name:
            temp_dir = Path(temp_dir_name)
            (temp_dir / "lvgl.h").write_text(stub_lvgl, encoding="utf-8")
            (temp_dir / "harness.c").write_text(harness, encoding="utf-8")
            binary = temp_dir / "tarot_catalog_test"
            compile_result = subprocess.run(
                [
                    "cc", "-std=c11", "-Wall", "-Wextra", "-Werror",
                    "-I", str(temp_dir), "-I", str(INCLUDE_DIR),
                    *(str(path) for path in asset_sources), str(temp_dir / "harness.c"),
                    "-o", str(binary),
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                check=False,
            )
            self.assertEqual(0, compile_result.returncode, compile_result.stdout)
            run_result = subprocess.run([str(binary)], check=False)
            self.assertEqual(0, run_result.returncode)


if __name__ == "__main__":
    unittest.main()
